### ISSUE TITLE
clarify if sponsor needs promotion

### ISSUE THREAD

**Issue by y3jo6** [yungyuc/first_day_with_python#18]
@yungyuc , I would some words in promotion post on JobSpace facebook page. It may look like below

開發環境採用 : infuseai.io, Effortless infrastructure for Machine Learning

I'm wondering if infuseai.io needs more?

**Comment by yungyuc** [comment]
@hlb, anything else you like to appear in our promotion?

**Comment by hlb** [comment]
I am not sure if this would be better:

> 現場有提供電腦，並且使用贊助商 InfuseAI 的 PrimeHub 平台進行教學。如果您習慣使用自己的電腦，仍然可以預裝好 Anaconda，並且預先下載我們的教學專案 （操作教學......）。

Our company intro is attached below, but since it is not a commercial event, I don't think we need more than one line mentioning and logo exposed ;-)

Our logos: https://drive.google.com/open?id=1-O4Rm3M9-S9Upp904QwYUXJgZxRlHhv1

# English version

InfuseAI was founded in 2018. We build high-quality software and services to help people work smarter and happier.

Our product "PrimeHub" is a software to help industry-wide AI/ML adoption by building the machine learning platform for on-premise or mixed-cloud environment. It helps enterprises to manage computing resources effortlessly, and let developers and data scientists focus on the developments of AI.

# Chinese version

InfuseAI 成立於 2018 年。我們打造高品質的軟體服務，讓人們聰明工作，樂在其中。

我們的產品 PrimeHub 是一套協助企業快速建構 AI/ML 深度學習平台的工具，降低企業導入 AI/ML 的技術門檻，並且輕鬆管理運算資源，讓開發人員和資料科學家可以更專注於 AI 的發展。

https://www.infuseai.io/

**Comment by y3jo6** [comment]
@hlb, except what YYC provided, I could put more words and logo on the
promotion.
Thanks for your example.

Yung-Yu Chen <notifications@github.com> 於 2018年11月22日 週四 下午3:28寫道：

**Comment by yungyuc** [comment]
@hlb I added the following sponsor promotion texts at 
http://bit.ly/fdp1812 :

> InfuseAI ( https://www.infuseai.io/ ) was founded in 2018. They build high-quality software and services to help people work smarter and happier. This bootcamp uses their product PrimeHub, an AI/ML platform in on-premise or mixed-cloud environment. PrimeHub helps enterprises manage computing resources effortlessly, and developers and data scientists focus on their jobs.

It seems I cannot add picture to event description for your logo.  We'll see if we can do it with other channel.  Let us know if anything should be changed or added.

**Comment by hlb** [comment]
@yungyuc looks awesome to me :)
